server:
  port: 8045

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: /**/
    username: /**/
    password: /**/
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: /**/
            client-secret: /**/
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  thymeleaf:
    prefix: classpath:/mail/templates/
    suffix: .html
    mode: HTML5

springdoc:
  paths-To-Match: /api/**


lotrel-mail:
  address: /**/
  password: /**/
  host: /**/
  port: /**/
  templates: mail/templates

lotrel-security:
  secret: /**/
  expiration: /**/
  redirectUrls:
    /**/



